services:
  api:
    build: .
    container_name: nest-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sistema-arquitetura
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: nest-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
